// Add action type constants below
// e.g. export const ACTION_DESCRIPTION = "ACTION_DESCRIPTION";
 export const CHANGE_COUNTRY = 'CHANGE_COUNTRY';
 export const CHANGE_COUNTRY_DATA = 'CHANGE_COUNTRY_DATA';
 export const CHANGE_DISASTER_TYPE_VIEW = 'CHANGE_DISASTER_TYPE_VIEW';